CREATE TABLE time_deposits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_type VARCHAR(64) NOT NULL,
    days INTEGER NOT NULL,
    balance NUMERIC(19, 2) NOT NULL
);

CREATE TABLE withdrawals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_deposit_id INTEGER NOT NULL REFERENCES time_deposits (id),
    amount NUMERIC(19, 2) NOT NULL,
    date DATE NOT NULL
);

CREATE INDEX withdrawals_time_deposit_id_idx ON withdrawals (time_deposit_id);
